Repository opendatahub-io/modelmesh-serving, pull requests merged in 2023-02, with the labels that each got.

#64 Update newTag to match the one in odh-manifests
  manifests/opendatahub/runtimes/kustomization.yaml
Labels: approved, lgtm

#61 Update kustomization for OVMS 2022.3
  config/runtimes/kustomization.yaml
Labels: approved, lgtm

#65 Sync upstream
  .github/workflows/build-and-push.yml
  .github/workflows/run-fvt.yml
  Dockerfile
  Dockerfile.develop
  README.md
  config/default/config-defaults.yaml
  config/dependencies/quickstart.yaml
  config/manager/manager.yaml
  config/runtimes/kustomization.yaml
  config/runtimes/torchserve-0.x.yaml
  controllers/modelmesh/cluster_config.go
  controllers/servingruntime_controller_test.go
  controllers/testdata/servingruntime_controller.golden
  docs/component-versions.md
  docs/install/install-script.md
  docs/quickstart.md
  docs/runtimes/README.md
  docs/runtimes/mlserver_custom.md
  fvt/predictor/predictor_suite_test.go
  fvt/scaleToZero/scaleToZero_suite_test.go
  go.mod
  go.sum
  pkg/config/config.go
  scripts/install.sh
  scripts/setup_user_namespaces.sh
Labels: approved, lgtm, ok-to-test

#67 Sync downstream manifests
  .gitignore
  manifests/kfdef.yaml
  manifests/opendatahub/base/kustomization.yaml
  manifests/opendatahub/base/params.env
  manifests/opendatahub/base/params.yaml
  manifests/opendatahub/default/config-defaults.yaml
  manifests/opendatahub/dependencies/fvt.yaml
  manifests/opendatahub/dependencies/quickstart.yaml
  manifests/opendatahub/dependencies/scripts/enable_auth.sh
  manifests/opendatahub/dependencies/scripts/kustomization.yaml
  manifests/opendatahub/manager/manager.yaml
  manifests/opendatahub/overlays/odh-model-controller/manager/kustomization.yaml
  manifests/opendatahub/overlays/odh-model-controller/manager/manager.yaml
  manifests/opendatahub/overlays/odh-model-controller/manager/servingruntimes_config.yaml
  manifests/opendatahub/overlays/odh-model-controller/rbac/role.yaml
  manifests/opendatahub/rbac/kustomization.yaml
  manifests/opendatahub/rbac/networkpolicy-etcd.yaml
  manifests/opendatahub/rbac/rolebinding-apps-metrics-access.yaml
  manifests/opendatahub/rbac/user_cluster_roles.yaml
  manifests/opendatahub/runtimes/ovms-1.x.yaml
  quickstart/etcd-secrets.yaml
  quickstart/etcd-users.yaml
  quickstart/openvino-serving-runtime.yaml
  quickstart/quickstart.sh
Labels: approved

#70 Fix e2e test and add openshift-ci make target
  Makefile
  config/dependencies/fvt.yaml
  fvt/fvtclient.go
Labels: approved, lgtm

#69 Create etcd secrets inside initContainer
  manifests/opendatahub/dependencies/quickstart.yaml
  quickstart/quickstart.sh
Labels: approved, lgtm

#72 add findutils package for openshift ci
  Dockerfile.develop
Labels: approved

#73 add modelmesh-serving-image option to accept a custom image url
  Makefile
  fvt/globals.go
  scripts/install.sh
Labels: approved

#74 create modelmesh-serving-sa and update oauth-proxy deployment
  config/default/config-defaults.yaml
  config/internal/base/deployment.yaml.tmpl
  config/rbac/common/kustomization.yaml
  config/rbac/common/modelmesh-serving-service-account.yaml
Labels: approved, lgtm

#75 Update test-data for unit test about sa
  controllers/testdata/test-config-defaults.yaml
Labels: approved
