Repository opendatahub-io/modelmesh-serving, pull requests merged in 2023-05, with the labels that each got.

#91 fix scripts for e2e
  opendatahub/scripts/repeat_fvt.sh
Labels: approved

#92 Sync between RHODS and ODH
  .github/pull_request_template.md
  config/internal/base/deployment.yaml.tmpl
  controllers/testdata/servingruntime_controller.golden
Labels: approved, lgtm

#94 opendatahub docs are updated
  opendatahub/docs/makefile-cheatsheet.md
  opendatahub/docs/manifests-management.md
Labels: approved, lgtm

#99 Quick Start Guide for basic,pvc,hpa
  opendatahub/docs/get-started-odh-modelserving.md
  opendatahub/quickstart/README.md
  opendatahub/quickstart/basic/README.md
  opendatahub/quickstart/basic/cleanup.sh
  opendatahub/quickstart/basic/deploy.sh
  opendatahub/quickstart/common_docs/modelmesh-cleanup.md
  opendatahub/quickstart/common_docs/modelmesh-install.md
  opendatahub/quickstart/common_manifests/allowAnyPvc-config.yaml
  opendatahub/quickstart/common_manifests/grpc-input-onnx.json
  opendatahub/quickstart/common_manifests/grpc-input-sklean.json
  opendatahub/quickstart/common_manifests/input-onnx.json
  opendatahub/quickstart/common_manifests/input-sklean.json
  opendatahub/quickstart/common_manifests/kfdef.yaml
  opendatahub/quickstart/common_manifests/openvino-inference-service.yaml
  opendatahub/quickstart/common_manifests/openvino-serving-runtime.yaml
  opendatahub/quickstart/common_manifests/proto/grpc_predict_v2.proto
  opendatahub/quickstart/common_manifests/proto/grpc_predict_v2_pb2.py
  opendatahub/quickstart/common_manifests/proto/grpc_predict_v2_pb2_grpc.py
  opendatahub/quickstart/common_manifests/sa_user.yaml
  opendatahub/quickstart/common_manifests/sklearn-storage-pvc.yaml
  opendatahub/quickstart/common_manifests/sklearn-storage.yaml
  opendatahub/quickstart/common_manifests/sklearn-storageUri-pvc.yaml
  opendatahub/quickstart/common_manifests/sklearn-storageUri.yaml
  opendatahub/quickstart/common_manifests/sklearn/mnist-svm.joblib
  opendatahub/quickstart/common_manifests/subs-odh-operator.yaml
  opendatahub/quickstart/env.sh
  opendatahub/quickstart/hpa/HPA_in_Modelmesh.png
  opendatahub/quickstart/hpa/README.md
  opendatahub/quickstart/hpa/cleanup.sh
  opendatahub/quickstart/hpa/deploy.sh
  opendatahub/quickstart/pvc/README.md
  opendatahub/quickstart/pvc/cleanup.sh
  opendatahub/quickstart/pvc/deploy.sh
  opendatahub/scripts/cleanup.sh
  opendatahub/scripts/install_odh.sh
  opendatahub/scripts/manifests/fvt/kustomization.yaml
  quickstart/README.md
  quickstart/etcd-secrets.yaml
  quickstart/etcd-users.yaml
  quickstart/input.json
  quickstart/quickstart.sh
  quickstart/sample-minio.yaml
Labels: approved

#101 Add downloading required binaries logic
  .gitignore
  opendatahub/scripts/deploy_fvt.sh
  opendatahub/scripts/env.sh
  opendatahub/scripts/install_odh.sh
Labels: approved

#100 doc-review-qs copy edit of quick starts for ModelMesh
  opendatahub/docs/get-started-odh-modelserving.md
  opendatahub/quickstart/README.md
  opendatahub/quickstart/basic/README.md
  opendatahub/quickstart/common_docs/modelmesh-cleanup.md
  opendatahub/quickstart/common_docs/modelmesh-install.md
  opendatahub/quickstart/hpa/README.md
  opendatahub/quickstart/pvc/README.md
Labels: approved, lgtm, needs-ok-to-test

#103 fix rhods-8873 and remove unnecessary manifests
  opendatahub/odh-manifests/model-mesh_stable/odh-model-controller/rbac/role.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-model-controller/rbac/role_binding.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/internal/base/deployment.yaml.tmpl
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/rbac/common/networkpolicy-webhook.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/webhook/kustomization.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/webhook/kustomizeconfig.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/webhook/manifests.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/webhook/service.yaml
Labels: approved, lgtm
