Repository opendatahub-io/modelmesh-serving, pull requests merged in 2023-09, with the labels that each got.

#174 [Sync] kserve/modelmesh-serving-main to main branch
  .github/workflows/build.yml
  .github/workflows/fvt.yml
  Dockerfile.develop
  Dockerfile.develop.ci
  Makefile
  config/crd/bases/serving.kserve.io_clusterservingruntimes.yaml
  config/crd/bases/serving.kserve.io_inferenceservices.yaml
  config/crd/bases/serving.kserve.io_servingruntimes.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/manifests.yaml
  controllers/hpa/hpa_reconciler.go
  controllers/modelmesh/modelmesh.go
  docs/component-versions.md
  docs/developer.md
  docs/examples/python_sdk_examples.ipynb
  docs/install/install-script.md
  docs/production-use/README.md
  docs/quickstart.md
  docs/release-process.md
  fvt/README.md
  fvt/fvtclient.go
  fvt/hpa/hpa_test.go
  go.mod
  go.sum
  scripts/self-signed-ca.sh
  scripts/setup_user_namespaces.sh
Labels: approved, lgtm

#181 update fast manifests based on main branch
  opendatahub/odh-manifests/model-mesh/base/kustomization.yaml
  opendatahub/odh-manifests/model-mesh/odh-model-controller/default/kustomization.yaml
  opendatahub/odh-manifests/model-mesh/odh-model-controller/overlays/odh/kustomization.yaml
  opendatahub/odh-manifests/model-mesh/odh-model-controller/overlays/odh/odh_model_controller_manager_patch.yaml
  opendatahub/odh-manifests/model-mesh/odh-model-controller/rbac/kserve_prometheus_clusterrole.yaml
  opendatahub/odh-manifests/model-mesh/odh-model-controller/rbac/role.yaml
  opendatahub/odh-manifests/model-mesh/odh-modelmesh-controller/crd/bases/serving.kserve.io_clusterservingruntimes.yaml
  opendatahub/odh-manifests/model-mesh/odh-modelmesh-controller/crd/bases/serving.kserve.io_inferenceservices.yaml
  opendatahub/odh-manifests/model-mesh/odh-modelmesh-controller/crd/bases/serving.kserve.io_servingruntimes.yaml
  opendatahub/odh-manifests/model-mesh/odh-modelmesh-controller/default/webhookcainjection_patch.yaml
  opendatahub/odh-manifests/model-mesh/odh-modelmesh-controller/overlays/odh/kustomization.yaml
  opendatahub/odh-manifests/model-mesh/odh-modelmesh-controller/webhook/manifests.yaml
Labels: approved, lgtm

#191 Fix fvt
  Makefile
  opendatahub/docs/manifests-management.md
Labels: lgtm

#190 Fix fvt
  Makefile
  opendatahub/docs/manifests-management.md
Labels: approved, lgtm

#196 Update Stable Manifest(main branch)
  opendatahub/odh-manifests/model-mesh/odh-model-controller/overlays/odh/odh_model_controller_manager_patch.yaml
  opendatahub/odh-manifests/model-mesh_stable/OWNERS
  opendatahub/odh-manifests/model-mesh_stable/base/kustomization.yaml
  opendatahub/odh-manifests/model-mesh_stable/base/params.env
  opendatahub/odh-manifests/model-mesh_stable/odh-model-controller/default/kustomization.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-model-controller/overlays/odh/kustomization.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-model-controller/overlays/odh/odh_model_controller_manager_patch.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-model-controller/rbac/role.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/certmanager/certificate.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/crd/bases/serving.kserve.io_clusterservingruntimes.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/crd/bases/serving.kserve.io_inferenceservices.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/crd/bases/serving.kserve.io_servingruntimes.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/crd/patches/webhook_in_predictors.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/crd/patches/webhook_in_servingruntimes.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/default/kustomization.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/default/manager_auth_proxy_patch.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/default/manager_webhook_patch.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/default/webhookcainjection_patch.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/dependencies/fvt.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/dependencies/quickstart.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/manager/kustomization.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/manager/manager.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/namespace-runtimes/kustomization.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/overlays/odh/kustomization.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/prometheus/monitor.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/rbac/cluster-scope/kustomization.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/rbac/cluster-scope/role.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/rbac/common/kustomization.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/rbac/namespace-scope/kustomization.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/rbac/namespace-scope/role.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/runtimes/kustomization.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/runtimes/mlserver-0.x.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/samples/servingruntime_pullerless.yaml
Labels: approved, lgtm, ok-to-test

#202 update tag to latest for main branch config folder manifests
  .github/workflows/fvt.yml
  config/default/config-defaults.yaml
  config/dependencies/quickstart.yaml
  config/manager/kustomization.yaml
  fvt/fvtclient.go
  opendatahub/kfdef/kfdef-stable.yaml
  opendatahub/odh-manifests/model-mesh/odh-modelmesh-controller/dependencies/quickstart.yaml
  opendatahub/odh-manifests/model-mesh/odh-modelmesh-controller/manager/kustomization.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/dependencies/quickstart.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/manager/kustomization.yaml
  opendatahub/scripts/deploy_fvt.sh
  opendatahub/scripts/download_images_on_nodes.sh
  opendatahub/scripts/manifests/fvt/fvt.yaml
  opendatahub/scripts/manifests/fvt/fvt_templates/kustomization.yaml
  opendatahub/scripts/manifests/fvt/fvt_templates/remove_etcd_patch.yaml
  opendatahub/scripts/manifests/fvt/kustomization.yaml
  opendatahub/scripts/manifests/fvt/quickstart.yaml
  opendatahub/scripts/manifests/params.env
  opendatahub/scripts/manifests/runtimes/kustomization.yaml
  scripts/download-images-on-nodes.sh
  version
Labels: approved, lgtm

#204 add max-retries for downloading-images
  opendatahub/scripts/download_images_on_nodes.sh
  opendatahub/scripts/utils.sh
  scripts/download-images-on-nodes.sh
Labels: approved, lgtm

#203 Create release-0.11branch
  .github/workflows/fvt.yml
  config/default/config-defaults.yaml
  config/dependencies/fvt.yaml
  config/dependencies/quickstart.yaml
  config/manager/kustomization.yaml
  controllers/testdata/servingruntime_controller_upstream.golden
  fvt/fvtclient.go
  opendatahub/kfdef/kfdef-stable.yaml
  opendatahub/odh-manifests/model-mesh/odh-modelmesh-controller/dependencies/quickstart.yaml
  opendatahub/odh-manifests/model-mesh/odh-modelmesh-controller/manager/kustomization.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/dependencies/fvt.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/dependencies/quickstart.yaml
  opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/manager/kustomization.yaml
  opendatahub/scripts/deploy_fvt.sh
  opendatahub/scripts/download_images_on_nodes.sh
  opendatahub/scripts/manifests/fvt/fvt.yaml
  opendatahub/scripts/manifests/fvt/fvt_templates/kustomization.yaml
  opendatahub/scripts/manifests/fvt/fvt_templates/remove_etcd_patch.yaml
  opendatahub/scripts/manifests/fvt/kustomization.yaml
  opendatahub/scripts/manifests/fvt/quickstart.yaml
  opendatahub/scripts/utils.sh
  scripts/download-images-on-nodes.sh
  version
Labels: approved, lgtm

#205 formatting README.md
  opendatahub/scripts/README.md
Labels: approved, lgtm, ok-to-test
